apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-demo.fullname" . }}
  labels:
    app: {{ include "my-demo.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      {{- if and ( eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "my-demo.name" . }}
